# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/ui_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log(object):
    def setupUi(self, log):
        log.setObjectName("log")
        log.resize(447, 23)
        self.label = QtWidgets.QLabel(log)
        self.label.setGeometry(QtCore.QRect(0, 0, 55, 16))
        self.label.setObjectName("label")

        self.retranslateUi(log)
        QtCore.QMetaObject.connectSlotsByName(log)

    def retranslateUi(self, log):
        _translate = QtCore.QCoreApplication.translate
        log.setWindowTitle(_translate("log", "Form"))
        self.label.setText(_translate("log", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    log = QtWidgets.QWidget()
    ui = Ui_log()
    ui.setupUi(log)
    log.show()
    sys.exit(app.exec_())
