# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI\\../telegram-spammer.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_page_new = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_new.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_new.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_new.setObjectName("btn_page_new")
        self.verticalLayout_2.addWidget(self.btn_page_new)
        self.btn_page_api_settings = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_api_settings.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_api_settings.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_api_settings.setObjectName("btn_page_api_settings")
        self.verticalLayout_2.addWidget(self.btn_page_api_settings)
        self.btn_page_account_settings = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_account_settings.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_account_settings.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton.isActive,\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.btn_page_account_settings.setObjectName("btn_page_account_settings")
        self.verticalLayout_2.addWidget(self.btn_page_account_settings)
        self.btn_page_help = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_help.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_help.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_help.setObjectName("btn_page_help")
        self.verticalLayout_2.addWidget(self.btn_page_help)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_new = QtWidgets.QWidget()
        self.page_new.setObjectName("page_new")
        self.label_1 = QtWidgets.QLabel(self.page_new)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 921, 41))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_1.setFont(font)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setStyleSheet("color: #FFF;")
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.label_7 = QtWidgets.QLabel(self.page_new)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.label_7.setStyleSheet("color: #FFF")
        self.label_7.setObjectName("label_7")
        self.sender_message = QtWidgets.QPlainTextEdit(self.page_new)
        self.sender_message.setGeometry(QtCore.QRect(140, 60, 301, 221))
        self.sender_message.setStyleSheet("background-color: #FFF")
        self.sender_message.setObjectName("sender_message")
        self.label_8 = QtWidgets.QLabel(self.page_new)
        self.label_8.setGeometry(QtCore.QRect(10, 300, 101, 16))
        self.label_8.setStyleSheet("color: #FFF")
        self.label_8.setObjectName("label_8")
        self.sender_attachment_type = QtWidgets.QComboBox(self.page_new)
        self.sender_attachment_type.setGeometry(QtCore.QRect(140, 300, 121, 21))
        self.sender_attachment_type.setStyleSheet("background-color: #FFF")
        self.sender_attachment_type.setEditable(False)
        self.sender_attachment_type.setObjectName("sender_attachment_type")
        self.sender_attachment_type.addItem("")
        self.sender_attachment_type.addItem("")
        self.sender_attachment_type.addItem("")
        self.sender_attachment_file = QtWidgets.QPushButton(self.page_new)
        self.sender_attachment_file.setGeometry(QtCore.QRect(140, 340, 121, 21))
        self.sender_attachment_file.setStyleSheet("background-color: #FFF")
        self.sender_attachment_file.setObjectName("sender_attachment_file")
        self.label_9 = QtWidgets.QLabel(self.page_new)
        self.label_9.setGeometry(QtCore.QRect(10, 380, 111, 16))
        self.label_9.setStyleSheet("color: #FFF")
        self.label_9.setObjectName("label_9")
        self.sender_contacts_file = QtWidgets.QPushButton(self.page_new)
        self.sender_contacts_file.setGeometry(QtCore.QRect(140, 380, 121, 21))
        self.sender_contacts_file.setStyleSheet("background-color: #FFF")
        self.sender_contacts_file.setObjectName("sender_contacts_file")
        self.label_10 = QtWidgets.QLabel(self.page_new)
        self.label_10.setGeometry(QtCore.QRect(470, 40, 111, 16))
        self.label_10.setStyleSheet("color: #FFF")
        self.label_10.setObjectName("label_10")
        self.sender_btn_start = QtWidgets.QPushButton(self.page_new)
        self.sender_btn_start.setGeometry(QtCore.QRect(0, 550, 141, 31))
        self.sender_btn_start.setStyleSheet("background-color: #FFF")
        self.sender_btn_start.setObjectName("sender_btn_start")
        self.label_11 = QtWidgets.QLabel(self.page_new)
        self.label_11.setGeometry(QtCore.QRect(10, 340, 101, 16))
        self.label_11.setStyleSheet("color: #FFF")
        self.label_11.setObjectName("label_11")
        self.label_attachment_file = QtWidgets.QLabel(self.page_new)
        self.label_attachment_file.setGeometry(QtCore.QRect(270, 340, 161, 16))
        self.label_attachment_file.setStyleSheet("color: #AAAAAA")
        self.label_attachment_file.setObjectName("label_attachment_file")
        self.label_contacts_file = QtWidgets.QLabel(self.page_new)
        self.label_contacts_file.setGeometry(QtCore.QRect(270, 380, 161, 16))
        self.label_contacts_file.setStyleSheet("color: #AAAAAA")
        self.label_contacts_file.setObjectName("label_contacts_file")
        self.label_12 = QtWidgets.QLabel(self.page_new)
        self.label_12.setGeometry(QtCore.QRect(10, 420, 111, 16))
        self.label_12.setStyleSheet("color: #FFF")
        self.label_12.setObjectName("label_12")
        self.sender_delay = QtWidgets.QLineEdit(self.page_new)
        self.sender_delay.setGeometry(QtCore.QRect(140, 420, 121, 22))
        self.sender_delay.setStyleSheet("background-color: #FFF")
        self.sender_delay.setObjectName("sender_delay")
        self.label_13 = QtWidgets.QLabel(self.page_new)
        self.label_13.setGeometry(QtCore.QRect(10, 460, 111, 16))
        self.label_13.setStyleSheet("color: #FFF")
        self.label_13.setObjectName("label_13")
        self.sender_messages_count = QtWidgets.QLineEdit(self.page_new)
        self.sender_messages_count.setGeometry(QtCore.QRect(140, 460, 121, 22))
        self.sender_messages_count.setStyleSheet("background-color: #FFF")
        self.sender_messages_count.setObjectName("sender_messages_count")
        self.label_14 = QtWidgets.QLabel(self.page_new)
        self.label_14.setGeometry(QtCore.QRect(10, 490, 111, 31))
        self.label_14.setStyleSheet("color: #FFF")
        self.label_14.setObjectName("label_14")
        self.sender_unqiue = QtWidgets.QCheckBox(self.page_new)
        self.sender_unqiue.setGeometry(QtCore.QRect(140, 500, 16, 20))
        self.sender_unqiue.setText("")
        self.sender_unqiue.setObjectName("sender_unqiue")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_new)
        self.textBrowser.setGeometry(QtCore.QRect(470, 60, 441, 601))
        self.textBrowser.setStyleSheet("background-color: #fff")
        self.textBrowser.setObjectName("textBrowser")
        self.sender_btn_clear_processed = QtWidgets.QPushButton(self.page_new)
        self.sender_btn_clear_processed.setGeometry(QtCore.QRect(170, 500, 191, 21))
        self.sender_btn_clear_processed.setStyleSheet("background-color: #FFF")
        self.sender_btn_clear_processed.setObjectName("sender_btn_clear_processed")
        self.stackedWidget.addWidget(self.page_new)
        self.page_api_settings = QtWidgets.QWidget()
        self.page_api_settings.setObjectName("page_api_settings")
        self.label = QtWidgets.QLabel(self.page_api_settings)
        self.label.setGeometry(QtCore.QRect(0, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFF;")
        self.label.setObjectName("label")
        self.input_api_id = QtWidgets.QLineEdit(self.page_api_settings)
        self.input_api_id.setGeometry(QtCore.QRect(160, 60, 141, 22))
        self.input_api_id.setStyleSheet("background-color: #FFF")
        self.input_api_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_api_id.setObjectName("input_api_id")
        self.input_api_hash = QtWidgets.QLineEdit(self.page_api_settings)
        self.input_api_hash.setGeometry(QtCore.QRect(160, 100, 141, 22))
        self.input_api_hash.setStyleSheet("background-color: #FFF")
        self.input_api_hash.setObjectName("input_api_hash")
        self.label_4 = QtWidgets.QLabel(self.page_api_settings)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_4.setStyleSheet("color: #FFF")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_api_settings)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_5.setStyleSheet("color: #FFF")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_api_settings)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 111, 16))
        self.label_6.setStyleSheet("color: #FFF")
        self.label_6.setObjectName("label_6")
        self.input_api_phone = QtWidgets.QLineEdit(self.page_api_settings)
        self.input_api_phone.setGeometry(QtCore.QRect(160, 140, 141, 22))
        self.input_api_phone.setStyleSheet("background-color: #FFF")
        self.input_api_phone.setObjectName("input_api_phone")
        self.btn_connect_api = QtWidgets.QPushButton(self.page_api_settings)
        self.btn_connect_api.setGeometry(QtCore.QRect(10, 200, 93, 28))
        self.btn_connect_api.setStyleSheet("background-color: #FFF")
        self.btn_connect_api.setObjectName("btn_connect_api")
        self.btn_disconnect_api = QtWidgets.QPushButton(self.page_api_settings)
        self.btn_disconnect_api.setGeometry(QtCore.QRect(130, 200, 93, 28))
        self.btn_disconnect_api.setStyleSheet("background-color: #FFF")
        self.btn_disconnect_api.setObjectName("btn_disconnect_api")
        self.label_20 = QtWidgets.QLabel(self.page_api_settings)
        self.label_20.setGeometry(QtCore.QRect(10, 260, 111, 16))
        self.label_20.setStyleSheet("color: #FFF")
        self.label_20.setObjectName("label_20")
        self.api_status_label = QtWidgets.QLabel(self.page_api_settings)
        self.api_status_label.setGeometry(QtCore.QRect(70, 260, 111, 16))
        self.api_status_label.setStyleSheet("color: #FFF")
        self.api_status_label.setObjectName("api_status_label")
        self.btn_refresh_api_status = QtWidgets.QPushButton(self.page_api_settings)
        self.btn_refresh_api_status.setGeometry(QtCore.QRect(150, 260, 71, 21))
        self.btn_refresh_api_status.setStyleSheet("background-color: #FFF")
        self.btn_refresh_api_status.setObjectName("btn_refresh_api_status")
        self.stackedWidget.addWidget(self.page_api_settings)
        self.page_account_settings = QtWidgets.QWidget()
        self.page_account_settings.setObjectName("page_account_settings")
        self.label_3 = QtWidgets.QLabel(self.page_account_settings)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 261, 41))
        self.label_3.setStyleSheet("color: #FFF;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_15 = QtWidgets.QLabel(self.page_account_settings)
        self.label_15.setGeometry(QtCore.QRect(0, 60, 131, 16))
        self.label_15.setStyleSheet("color: #FFF")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_account_settings)
        self.label_16.setGeometry(QtCore.QRect(0, 100, 121, 16))
        self.label_16.setStyleSheet("color: #FFF")
        self.label_16.setObjectName("label_16")
        self.account_firstname = QtWidgets.QLineEdit(self.page_account_settings)
        self.account_firstname.setGeometry(QtCore.QRect(140, 60, 251, 22))
        self.account_firstname.setStyleSheet("background-color: #FFF")
        self.account_firstname.setObjectName("account_firstname")
        self.account_lastname = QtWidgets.QLineEdit(self.page_account_settings)
        self.account_lastname.setGeometry(QtCore.QRect(140, 100, 251, 22))
        self.account_lastname.setStyleSheet("background-color: #FFF")
        self.account_lastname.setObjectName("account_lastname")
        self.label_17 = QtWidgets.QLabel(self.page_account_settings)
        self.label_17.setGeometry(QtCore.QRect(0, 140, 121, 16))
        self.label_17.setStyleSheet("color: #FFF")
        self.label_17.setObjectName("label_17")
        self.account_bio = QtWidgets.QPlainTextEdit(self.page_account_settings)
        self.account_bio.setGeometry(QtCore.QRect(140, 140, 251, 87))
        self.account_bio.setStyleSheet("background-color: #FFF")
        self.account_bio.setObjectName("account_bio")
        self.label_18 = QtWidgets.QLabel(self.page_account_settings)
        self.label_18.setGeometry(QtCore.QRect(0, 250, 121, 16))
        self.label_18.setStyleSheet("color: #FFF")
        self.label_18.setObjectName("label_18")
        self.account_avatar_file = QtWidgets.QPushButton(self.page_account_settings)
        self.account_avatar_file.setGeometry(QtCore.QRect(140, 250, 111, 21))
        self.account_avatar_file.setStyleSheet("background-color: #FFF")
        self.account_avatar_file.setObjectName("account_avatar_file")
        self.account_avatar_label = QtWidgets.QLabel(self.page_account_settings)
        self.account_avatar_label.setGeometry(QtCore.QRect(260, 250, 211, 16))
        self.account_avatar_label.setStyleSheet("color: #AAA")
        self.account_avatar_label.setText("")
        self.account_avatar_label.setObjectName("account_avatar_label")
        self.account_save_btn = QtWidgets.QPushButton(self.page_account_settings)
        self.account_save_btn.setGeometry(QtCore.QRect(0, 300, 111, 31))
        self.account_save_btn.setStyleSheet("background-color: #FFF")
        self.account_save_btn.setObjectName("account_save_btn")
        self.stackedWidget.addWidget(self.page_account_settings)
        self.page_help = QtWidgets.QWidget()
        self.page_help.setObjectName("page_help")
        self.label_19 = QtWidgets.QLabel(self.page_help)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 481, 41))
        self.label_19.setStyleSheet("color: #fff")
        self.label_19.setObjectName("label_19")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_help)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 50, 921, 621))
        self.textBrowser_2.setStyleSheet("background-color: #fff")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.stackedWidget.addWidget(self.page_help)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram spammer"))
        self.btn_page_new.setText(_translate("MainWindow", "Рассылка"))
        self.btn_page_api_settings.setText(_translate("MainWindow", "Настройки API"))
        self.btn_page_account_settings.setText(_translate("MainWindow", "Настройки аккаунта"))
        self.btn_page_help.setText(_translate("MainWindow", "Инструкция"))
        self.label_1.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Новая рассылка</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Сообщение"))
        self.label_8.setText(_translate("MainWindow", "Тип вложения"))
        self.sender_attachment_type.setItemText(0, _translate("MainWindow", "Пусто"))
        self.sender_attachment_type.setItemText(1, _translate("MainWindow", "Фото"))
        self.sender_attachment_type.setItemText(2, _translate("MainWindow", "Видео"))
        self.sender_attachment_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_9.setText(_translate("MainWindow", "Список контактов"))
        self.sender_contacts_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_10.setText(_translate("MainWindow", "Лог выполнения"))
        self.sender_btn_start.setText(_translate("MainWindow", "Начать рассылку"))
        self.label_11.setText(_translate("MainWindow", "Файл вложения"))
        self.label_attachment_file.setText(_translate("MainWindow", "Название файла"))
        self.label_contacts_file.setText(_translate("MainWindow", "Название файла"))
        self.label_12.setText(_translate("MainWindow", "Задержка (в сек)"))
        self.label_13.setText(_translate("MainWindow", "Кол-во сообщений"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Уникальные<br/>сообщения</p></body></html>"))
        self.sender_btn_clear_processed.setText(_translate("MainWindow", "Очистить список отправленных"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Настройки API</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "API id"))
        self.label_5.setText(_translate("MainWindow", "API hash"))
        self.label_6.setText(_translate("MainWindow", "Номер телефона"))
        self.btn_connect_api.setText(_translate("MainWindow", "Подключить"))
        self.btn_disconnect_api.setText(_translate("MainWindow", "Отключить"))
        self.label_20.setText(_translate("MainWindow", "Статус:"))
        self.api_status_label.setText(_translate("MainWindow", "Отключено"))
        self.btn_refresh_api_status.setText(_translate("MainWindow", "Обновить"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Настройки Аккаунта</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Имя"))
        self.label_16.setText(_translate("MainWindow", "Фамилия"))
        self.label_17.setText(_translate("MainWindow", "Описание"))
        self.label_18.setText(_translate("MainWindow", "Аватарка"))
        self.account_avatar_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.account_save_btn.setText(_translate("MainWindow", "Сохранить"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Инструкция</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Порядок работы:</span><br />1) Настройка API</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2) Рассылка</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">1 шаг Настройка API</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Необходимо добавить аккаунт<br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">На сайте my.telegram.org регистрируем новое telegram приложение и получаем api_id и api_key (либо используем мои, но если часто их использовать, то просто аккаунт заблокируют)<br />api_id: <span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#f78c6c;\">29492858 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">api_hash: <span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#c3e88d;\">2bfebf140a4f000b1dcc1899e669967c</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#c3e88d;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\">1) В поле api_phone вводим номер телефона </span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; font-weight:600; color:#000000;\">!!!обязательно с + в начале!!!</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br />2) Нажимаем на кнопку &quot;Подключить&quot; Открывается окно (необходимо подождать секунд 10)<br />3) В него вводим ещё раз номер телефона а потом код, который пришёл в телеграм (либо сразу код, читаем что просят в консоли)<br />4) Нажимаем на кнопку &quot;Обновить&quot;, удостоверяемся, что статус - Подключено<br /><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:12pt; font-weight:600; color:#000000;\">2 шаг Рассылка</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\">После настройки можно сделать рассылку:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br />1) Указываем сообщение<br />2) выбираем тип файла<br />3) загружаем файл (если загрузить файл и выбрать тип &quot;Пусто&quot;, то файл не отправится),<br />4) загружаем список контактов (обычный .txt файл с номером в каждой строчке)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\">5) Выбираем задержку, желательно 300 секунд, чтобы не прилетел бан</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\">6) Выбираем количество сообщений (оставляем поле пустым, если хотим, чтобы отправились все сообщения<br />7) Выбираем уникальные сообщения - при включении этой функции если второй раз включить рассылку, то сообщение не отправится второй раз тем, кому оно уже пришло. Кнопка - &quot;Очистить список отправленных&quot; чтобы очистить список тех, кому сообщение уже было отправлено<br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; font-weight:600; color:#000000;\">!!! Ультра важно !!!</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br />Если закрыть программу - рассылка перестанет работать<br /><br />Единственный способ прекратить рассылку - закрыть программу<br /><br />Единственный способ запустить новую рассылку - закрыть программу, изменить сообщение, вложение и тд и запустить<br /><br />Если рассылка не работает, то проверяем подключение в настройках API, отключаемся и подключаемся заново, нажимаем кнопку &quot;обновить&quot;, чтобы удостовериться, что статус &quot;подключено&quot;<br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\">Сообщение &quot;Не получилось найти контакт&quot; означает, что такой аккаунт в телеграме не зарегистрирован, либо недоступен для добавления по номеру телефона<br /><br /></span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:12pt; font-weight:600; color:#000000;\">Настройки Аккаунта</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br />Этот раздел чтобы через Telegram Spamer изменить информацию в профиле</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br /></span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; font-weight:600; color:#000000;\">!!! Не отображает значения, которые стояли в телеграме изначально, или которые мы меняли руками в телеграме потом</span><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; font-weight:600; color:#000000;\">!!! программа ультра сырая и багованная, так как это мой первый опыт создания десктопных приложений</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; font-weight:600; color:#000000;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; font-weight:600; color:#000000;\"><br />Автор: Алексей Кесслер</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; font-weight:600; color:#000000;\">Telegram: Aleksey_Kessler</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:8pt; color:#000000;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
